database:
  type: mysql
  mysql:
    host: localhost
    port: 3306
    database: playercustomisation
    username: root
    password: "changeme"
    pool-size: 10

# Cache settings (in milliseconds)
cache:
  player-data-ttl: 30000  # 30 seconds
  permission-ttl: 5000    # 5 seconds

# Default values
defaults:
  fallback-rank: "default"
  name-color: "&f"
  material: NAME_TAG

# Animation settings
animations:
  rainbow:
    enabled: true
    speed: 5
  gradient:
    enabled: true
    speed: 10

# Define your ranks and their permissions
# Rank names MUST match your LuckPerms group names exactly!
ranks:
  default:
    colors: false
    gradients: false
    rainbow: false
    prefix: false
    suffix: false
    nickname: false
    
  vip:
    colors: true
    gradients: false
    rainbow: false
    prefix: true
    suffix: true
    nickname: true
    
  vip+:
    colors: true
    gradients: true
    rainbow: false
    prefix: true
    suffix: true
    nickname: true
    
  mvp:
    colors: true
    gradients: true
    rainbow: false
    prefix: true
    suffix: true
    nickname: true
    
  mvp+:
    colors: true
    gradients: true
    rainbow: true
    prefix: true
    suffix: true
    nickname: true
    
  supporter:
    colors: true
    gradients: false
    rainbow: false
    prefix: true
    suffix: true
    nickname: true
    
  patron:
    colors: true
    gradients: true
    rainbow: false
    prefix: true
    suffix: true
    nickname: true
    
  devoted:
    colors: true
    gradients: true
    rainbow: true
    prefix: true
    suffix: true
    nickname: true
    custom-tags: true
    
  legend:
    colors: true
    gradients: true
    rainbow: true
    prefix: true
    suffix: true
    nickname: true
    custom-tags: true

# Nickname settings
nickname:
  min-length: 3
  max-length: 16
  validation-pattern: "^[a-zA-Z0-9_]{3,16}$"
  # Blocked nicknames (case insensitive)
  blocked-names:
    - "admin"
    - "owner"
    - "staff"
    - "moderator"
    - "notch"
    - "server"
    - "console"