# == GENERAL SETTINGS ==
database:
  type: mysql
  mysql:
    host: localhost
    port: 3306
    database: playercustomisation
    username: root
    password: "changeme"
    pool-size: 10

# Cache settings (in milliseconds)
cache:
  player-data-ttl: 30000  # 30 seconds
  permission-ttl: 5000    # 5 seconds

# Default values
defaults:
  fallback-rank: "default"
  name-color: "&f"
  material: NAME_TAG

# Animation settings
animations:
  rainbow:
    enabled: true
    speed: 5
  gradient:
    enabled: true
    speed: 10

# == RANK SETTINGS ==

# Define your ranks and their permissions
# Rank names MUST match your LuckPerms group names exactly!
ranks:
  default:
    colors: false
    gradients: false
    rainbow: false
    prefix: false
    suffix: false
    nickname: false
    
  member:
    colors: true
    gradients: true
    rainbow: false
    prefix: true
    suffix: true
    nickname: true
    
  donator:
    colors: true
    gradients: true
    rainbow: true
    prefix: true
    suffix: true
    nickname: true
    
  supporter:
    colors: true
    gradients: false
    rainbow: false
    prefix: true
    suffix: true
    nickname: true
    
  patron:
    colors: true
    gradients: true
    rainbow: false
    prefix: true
    suffix: true
    nickname: true
    
  patron+:
    colors: true
    gradients: true
    rainbow: true
    prefix: true
    suffix: true
    nickname: true
    custom-tags: true
    
  owner:
    colors: true
    gradients: true
    rainbow: true
    prefix: true
    suffix: true
    nickname: true
    custom-tags: true

# == NICKNAME SETTINGS ==
nickname:
  min-length: 3
  max-length: 16
  validation-pattern: "^[a-zA-Z0-9_]{3,16}$"
  # Blocked nicknames (case insensitive)
  blocked-names:
    - "admin"
    - "owner"
    - "staff"
    - "moderator"
    - "notch"
    - "server"
    - "console"

# == NAMETAG SETTINGS ==

nametags:
  # Enable nametag system (set to false if using external plugins)
  enabled: true
  
  # Use TAB plugin for display (recommended)
  # If true, HxPrefix only manages data and TAB handles display
  # If false, would use native implementation (not currently available)
  use-tab-integration: true
  
  # These settings are for future native implementation
  show-prefix: true
  show-suffix: true
  update-on-join: true
  join-delay: 20
  
  # TAB integration settings
  tab:
    # Force refresh on changes (may cause flicker)
    force-refresh: false
    # Refresh delay in ticks (20 = 1 second)
    refresh-delay: 10