database:
  type: "mysql"  # Options: "sqlite" or "mysql"
  # SQLite settings (when type is "sqlite")
  file: "../../shared-data/customization.db"
  # MySQL settings (when type is "mysql")
  host: "mysql"  # Docker service name or IP
  port: 3306
  database: "player_customization"
  username: "minecraft"
  password: "minecraft_password"
  # Common settings
  connection_pool_size: 10
  timeout: 30000
  backup_interval: 24

multi_server:
  enabled: true
  sync_interval: 5
  cross_server_notifications: true

# Predefined color options
colors:
  basic: ["red", "blue", "green", "yellow", "purple", "orange", "pink", "cyan", "white", "gray", "black"]
  gradients:
    preset:
      - "red:blue"
      - "green:yellow"
      - "purple:pink"
      - "gold:orange"
      - "cyan:white"
      - "lime:green"

# Prefix definitions
prefixes:
  player:
    base_text: ""
    colors: []
    gradients: []
    custom_allowed: false
  supporter:
    base_text: "[SUPPORTER]"
    colors: ["red", "blue", "green", "yellow", "purple", "orange", "pink", "cyan", "white", "gray", "black"]
    gradients: []
    custom_allowed: false
  patron:
    base_text: "[PATRON]"
    colors: ["red", "blue", "green", "yellow", "purple", "orange", "pink", "cyan", "white", "gray", "black"]
    gradients: ["red:blue", "green:yellow", "purple:pink", "gold:orange", "cyan:white", "lime:green"]
    custom_allowed: false
  devoted:
    base_text: "[DEVOTED]"
    colors: ["all"]
    gradients: ["all"]
    custom_allowed: true

# Event prefixes (available to all ranks when earned)
event_prefixes:
  pride:
    text: "[Pride]"
    colors: ["rainbow"]
    available_dates: ["june"]
  halloween:
    text: "[Spooky]"
    colors: ["orange", "black"]
    available_dates: ["october"]
  christmas:
    text: "[Festive]"
    colors: ["red", "green"]
    available_dates: ["december"]

# Cache settings
cache:
  player_data_expire: 300
  max_cached_players: 200

# GUI settings
gui:
  sounds:
    click: "UI_BUTTON_CLICK"
    success: "ENTITY_EXPERIENCE_ORB_PICKUP"
    error: "ENTITY_VILLAGER_NO"
  particles:
    success: "VILLAGER_HAPPY"
    apply_change: "ENCHANTMENT_TABLE"

# Custom prefix settings
custom_prefixes:
  max_length: 16
  min_length: 1
  cooldown_days: 30
  forbidden_words: ["admin", "staff", "mod", "owner", "op"]
  approval_required: true

# Nickname settings
nicknames:
  max_length: 16
  min_length: 3
  allow_colors: true
  allow_special_chars: false