database:
  type: "mysql"  # Options: "sqlite" or "mysql"
  # SQLite settings (when type is "sqlite")
  file: "../../shared-data/customization.db"
  # MySQL settings (when type is "mysql")
  host: "customisation-mysql"  # Docker service name
  port: 3306
  database: "playercustomisation"
  username: "playercustomisation"
  password: "minecraft_password"
  # Common settings
  connection_pool_size: 10
  timeout: 30000
  backup_interval: 24

multi_server:
  enabled: true
  sync_interval: 5
  cross_server_notifications: true

# Predefined color options
colors:
  basic: ["red", "blue", "green", "yellow", "purple", "orange", "pink", "cyan", "white", "gray", "black"]
  gradients:
    preset:
      - "red:blue"
      - "green:yellow"
      - "purple:pink"
      - "gold:orange"
      - "cyan:white"
      - "lime:green"

# Prefix definitions
prefixes:
  player:
    base_text: ""
    colors: []
    gradients: []
    custom_allowed: false
  supporter:
    base_text: "[SUPPORTER]"
    colors: ["red", "blue", "green", "yellow", "purple", "orange", "pink", "cyan", "white", "gray", "black"]
    gradients: []
    custom_allowed: false
  patron:
    base_text: "[PATRON]"
    colors: ["red", "blue", "green", "yellow", "purple", "orange", "pink", "cyan", "white", "gray", "black"]
    gradients: ["red:blue", "green:yellow", "purple:pink", "gold:orange", "cyan:white", "lime:green"]
    custom_allowed: false
  devoted:
    base_text: "[DEVOTED]"
    colors: ["all"]
    gradients: ["all"]
    custom_allowed: true

# Event prefixes (available to all ranks when earned)
# 
# TO ADD A NEW TAG: Just add a new section with:
#   text: "YourWord"           - The word for the tag
#   gradient: "color1:color2"  - Two colors for the gradient
#   available_dates: ["month"] - Optional: when it's available (remove for always)
#
# The system will automatically:
#   - Make it BOLD and UPPERCASE: [YOURWORD]
#   - Apply the gradient colors
#   - Make it available to all ranks
#
# Available colors: 
#   Named: red, blue, green, yellow, purple, orange, pink, cyan, white, gray, black, gold, lime, aqua
#   Hex: #FF0000, #00FF00, #0000FF, etc. (any #RRGGBB format)
#
event_prefixes:
  pride:
    text: "Pride"
    gradient: "red:purple"  # Simple gradient definition
    available_dates: ["june"]
  halloween:
    text: "Spooky"
    gradient: "orange:black"
    available_dates: ["october"]
  christmas:
    text: "Festive" 
    gradient: "red:green"
    available_dates: ["december"]
  cool:
    text: "Cool"
    gradient: "blue:cyan"
    # No available_dates means always available
  epic:
    text: "Epic"
    gradient: "purple:pink"
  vip:
    text: "VIP"
    gradient: "gold:yellow"
  legend:
    text: "Legend"
    gradient: "red:orange"
  neon:
    text: "Neon"
    gradient: "#FF00FF:#00FFFF"  # Example with hex colors

# Cache settings
cache:
  player_data_expire: 300
  max_cached_players: 200

# GUI settings
gui:
  sounds:
    click: "UI_BUTTON_CLICK"
    success: "ENTITY_EXPERIENCE_ORB_PICKUP"
    error: "ENTITY_VILLAGER_NO"
  particles:
    success: "VILLAGER_HAPPY"
    apply_change: "ENCHANTMENT_TABLE"

# Custom prefix settings
custom_prefixes:
  max_length: 16
  min_length: 1
  cooldown_days: 30
  forbidden_words: ["admin", "staff", "mod", "owner", "op"]
  approval_required: true

# Nickname settings
nicknames:
  max_length: 16
  min_length: 3
  allow_colors: true
  allow_special_chars: false