# PlayerCustomisation Configuration
# Define what each rank can access

database:
  type: mysql
  mysql:
    host: localhost
    port: 3306
    database: playercustomisation
    username: root
    password: "changeme"

# Define your ranks and their permissions
# Rank names MUST match your LuckPerms group names exactly!
ranks:
  default:
    colors: false
    gradients: false
    rainbow: false
    prefix: false
    suffix: false
    nickname: false
    
  vip:
    colors: true
    gradients: false
    rainbow: false
    prefix: true
    suffix: false
    nickname: true
    # Limit which prefixes they can use (optional)
    prefix-whitelist:
      - "VIP"
      - "MEMBER"
    
  vip+:
    colors: true
    gradients: true
    rainbow: false
    prefix: true
    suffix: true
    nickname: true
    prefix-whitelist:
      - "VIP"
      - "VIP+"
      - "ELITE"
    
  premium:
    colors: true
    gradients: true
    rainbow: true
    prefix: true
    suffix: true
    nickname: true
    custom-tags: true
    # No whitelist = can use any prefix from prefix.yml

# Nickname settings
nickname:
  min-length: 3
  max-length: 16
  # Blocked nicknames (case insensitive)
  blocked-names:
    - "admin"
    - "owner"
    - "staff"
    - "moderator"
    - "notch"

# Messages
messages:
  prefix: "&8[&bCustom&8] "
  no-permission: "{prefix}&cYou don't have permission!"
  no-permission-rank: "{prefix}&cYour rank ({rank}) doesn't have access to this feature!"
  color-changed: "{prefix}&aColor changed!"
  gradient-changed: "{prefix}&aGradient applied!"
  prefix-changed: "{prefix}&aPrefix set to: {value}"
  suffix-changed: "{prefix}&aSuffix set to: {value}"
  nickname-changed: "{prefix}&aNickname set to: {value}"
  nickname-reset: "{prefix}&aNickname removed!"
  invalid-nickname: "{prefix}&cNickname must be alphanumeric and {min}-{max} characters!"
  value-reset: "{prefix}&aReset to default!"