name: PlayerCustomisation
version: '${project.version}'
main: com.yourserver.playercustomisation.PlayerCustomisation
api-version: '1.21'
authors: [YourServer]
description: Simple player customisation plugin
depend: [LuckPerms]
softdepend: [PlaceholderAPI]

commands:
  color:
    description: Opens color selection GUI
    usage: /<command>
    aliases: [colors, namecolor]
  prefix:
    description: Opens prefix selection GUI  
    usage: /<command>
    aliases: [prefixes, tag]
  suffix:
    description: Opens suffix selection GUI
    usage: /<command>
    aliases: [suffixes]
  nick:
    description: Sets or removes nickname
    usage: /<command> <nickname|off>
    aliases: [nickname]
  requesttag:
    description: Request custom tag
    usage: /<command> <tag>
    aliases: [customtag]
  managetags:
    description: Staff command to review tags
    usage: /<command>
    permission: playercustomisation.admin.tags
  pcreload:
    description: Reload configuration
    usage: /<command>
    permission: playercustomisation.admin.reload
  pc-internal:
    description: Internal command for GUI interactions
    usage: /<command>

# Only admin permissions remain
permissions:
  playercustomisation.admin:
    default: op
    description: All admin permissions
    children:
      playercustomisation.admin.tags: true
      playercustomisation.admin.reload: true
      playercustomisation.admin.bypass: true
  playercustomisation.admin.tags:
    default: op
    description: Manage custom tag requests
  playercustomisation.admin.reload:
    default: op
    description: Reload plugin configuration
  playercustomisation.admin.bypass:
    default: op
    description: Bypass rank restrictions