name: HxPrefix
version: '${project.version}'
main: dev.hxrry.hxprefix.HxPrefix 
api-version: "26.1"
author: hxrry
description: a prefix, suffix and name management plugin angled at velocity networks
website: info.hxrry.dev

softdepend:
  - LuckPerms
  - PlaceholderAPI
  - Vault

libraries:
  - org.xerial:sqlite-jdbc:3.46.0.0
  - org.postgresql:postgresql:42.7.3
  - com.zaxxer:HikariCP:5.1.0
  - com.github.ben-manes.caffeine:caffeine:3.1.8

permissions:
  hxprefix.tag:
    description: request custom tags
    default: true
  hxprefix.staff:
    description: staff name protection for nicknames
    default: op
  hxprefix.bypass.cooldown:
    description: bypass nickname cooldown
    default: op