name: HxPrefix
version: 0.1.0
main: dev.hxrry.hxprefix.HxPrefix 
api-version: "1.21"
author: hxrry
description: a prefix, suffix and name management plugin angled at velocity networks
website: info.hxrry.dev

softdepend:
  - LuckPerms
  - PlaceholderAPI
  - ProtocolLib
  - Vault

commands:
  prefix:
    description: manage your prefix
    usage: /<command> [prefix|off]
    aliases: []
    permission: hxprefix.use
    
  suffix:
    description: manage your suffix
    usage: /<command> [suffix|off]
    aliases: []
    permission: hxprefix.use
    
  colour:
    description: change your names colour
    usage: /<command> [colour|off]
    aliases: [color]  # silly american spelling alias
    permission: hxprefix.use
    
  nick:
    description: set your nickname
    usage: /<command> [nickname|off]
    aliases: []
    permission: hxprefix.use
    
  # admin command - using hxprefix for admin functions
  hxprefix:
    description: HxPrefix admin commands
    usage: /<command> [reload|tags|reset|info|cache|migrate]
    aliases: []
    permission: hxprefix.admin

permissions:
  hxprefix.use:
    description: base permission to use HxPrefix features
    default: true
  hxprefix.colour:
    description: change name colour
    default: true
  hxprefix.prefix:
    description: change prefix
    default: true
  hxprefix.suffix:
    description: change suffix
    default: true
  hxprefix.nickname:
    description: use nickname command
    default: true
  hxprefix.tag:
    description: request custom tags
    default: true
  hxprefix.admin:
    description: Admin commands
    default: op