name: PlayerCustomization
version: '${project.version}'
main: com.prefix27.customization.PlayerCustomizationPlugin
api-version: '1.21'
authors: [prefix27]
description: A plugin for player name colors, prefixes, and nicknames
website: https://github.com/prefix27/customization

depend: [LuckPerms]
softdepend: [PlaceholderAPI, VentureChat]

commands:
  customize:
    description: Open the main customization GUI
    usage: /<command>
    aliases: [style]
    permission: customization.use
  color:
    description: Direct access to color selection GUI
    usage: /<command>
    aliases: [colour]
    permission: customization.use
  prefix:
    description: Direct access to prefix selection GUI
    usage: /<command>
    permission: customization.use
  nick:
    description: Set your nickname
    usage: /<command> <name>
    permission: customization.nick
  gradient:
    description: Direct access to gradient builder
    usage: /<command>
    permission: customization.patron
  customization:
    description: Admin commands for customization management
    usage: /<command> <admin|reload|reset>
    permission: customization.admin

permissions:
  customization.use:
    description: Basic access to customization features
    default: true
  customization.supporter:
    description: Access to supporter rank features
    default: false
  customization.patron:
    description: Access to patron rank features
    default: false
  customization.devoted:
    description: Access to devoted rank features
    default: false
  customization.nick:
    description: Ability to set nicknames
    default: false
  customization.admin:
    description: Access to admin commands
    default: op
  customization.*:
    description: Access to all customization features
    default: op
    children:
      customization.use: true
      customization.supporter: true
      customization.patron: true
      customization.devoted: true
      customization.nick: true
      customization.admin: true